datasets:
  traj_align:
    split: train
    data_type: trajectories
    build_info:
      # storage: <internal_user_root>/gpt_datasets/minigpt4_datasets/traj/aug7/
      # storage: <internal_user_root>/gpt_datasets/minigpt4_datasets/traj/traj_1d_169anchors/
      # storage: <internal_user_root>/gpt_datasets/minigpt4_datasets/traj/traj_14jul_01/
      # storage: <local_dataset_root>/waymo/training_interactive_processed3/*
      # storage: <internal_user_root>/waymo_dataset/training_interactive_processed3/*
      # storage: <internal_user_root>/waymo_dataset/training_interactive_gameformer/*
      # storage: <internal_user_root>/waymo_dataset/training_interactive_gameformer/*
      
  traj_align_valid:
    split: valid
    data_type: trajectories
    build_info:
      # storage: <internal_user_root>/gpt_datasets/minigpt4_datasets/traj/aug7/
      # storage: <internal_user_root>/gpt_datasets/minigpt4_datasets/traj/traj_1d_169anchors/
      # storage: <internal_user_root>/gpt_datasets/minigpt4_datasets/traj/traj_14jul_01/
      # storage: <local_dataset_root>/waymo/validation_interactive_processed3/*
      # storage: <internal_user_root>/waymo_dataset/training_interactive_processed3/*
      # storage: <internal_user_root>/waymo_dataset/validation_interactive_processed3/*
      # storage: <internal_user_root>/waymo_dataset/validation_interactive_gameformer/*
      # storage: <internal_user_root>/waymo_dataset/validation_interactive_gameformer_1k/*
      # storage: <internal_user_root>/waymo_dataset/training_interactive_gameformer_10k/*

  # traj_align_kw61078:
  #   split: train
  #   data_type: trajectories
  #   build_info:
  #     # storage: <internal_user_root>/gpt_datasets/minigpt4_datasets/traj/aug7/
  #     # storage: <internal_user_root>/gpt_datasets/minigpt4_datasets/traj/traj_1d_169anchors/
  #     # storage: <internal_user_root>/gpt_datasets/minigpt4_datasets/traj/traj_14jul_01/
  #     storage: <local_dataset_root>/waymo/training_interactive_processed3/*
  #     # storage: <internal_user_root>/waymo_dataset/training_interactive_processed3/*