import torch
from .GameFormer_modules import *


class InitialDecoder_2(nn.Module):
    def __init__(self, modalities, neighbors, future_len, act=False):
        super(InitialDecoder_2, self).__init__()
        dim = 256
        self._modalities = modalities
        self.act = act
        if act:
            self.act_embedding = nn.Embedding(5, dim)
            print("ACT DECODER ACTIVATED")
        self.multi_modal_query_embedding = nn.Embedding(modalities, dim)
        self.agent_query_embedding = nn.Embedding(neighbors+1, dim)
        self.query_encoder = CrossTransformer()
        self.predictor = GMMPredictor(future_len)
        self.register_buffer('modal', torch.arange(modalities).long())
        self.register_buffer('agent', torch.arange(neighbors+1).long())

    def forward(self, id, current_state, encoding, mask, act=None):
        # get query
        multi_modal_query = self.multi_modal_query_embedding(self.modal) # uses embedding to generate multimodal queries, input size = n_modalities.  shape = [M, dim=256] No batch dim
        agent_query = self.agent_query_embedding(self.agent[id]) # uses embedding with input shape n_neighbors, shape = [dim] No batch dim
        multi_modal_agent_query = multi_modal_query + agent_query[None, :] # shape = [M, dim] No batch dim
        query = encoding[:, None, id] + multi_modal_agent_query # shape = [batch, M, dim]

        if act is not None:
            query = query + act[:,None,:] # act embedding is generated by the LLM
            # query = query + self.act_embedding(act.int())[:,None,:]

        # decode trajectories
        query_content = self.query_encoder(query, encoding, encoding, mask) # [M, dim]
        predictions, scores = self.predictor(query_content) # predicictions is a [M: modilities, T: time to predict, 4: GMM parameters]

        # post process
        predictions[..., :2] += current_state[:, None, None, :2] # adding the current state x,t locations to the obtained x,y mean of the GMM

        return query_content, predictions, scores

class Encoder_01_2(nn.Module):
    def __init__(self, neighbors_to_predict, layers=6, act=False):
        super(Encoder_01_2, self).__init__()
        heads, dim, dropout = 8, 256, 0.1
        self._neighbors = neighbors_to_predict
        self.agent_encoder = AgentEncoder()
        self.ego_encoder = AgentEncoder()
        self.lane_encoder = LaneEncoder()
        self.crosswalk_encoder = CrosswalkEncoder()
            
    def segment_map(self, map, map_encoding):
        stride = 10
        B, N_e, N_p, D = map_encoding.shape

        # segment map
        map_encoding = F.max_pool2d(map_encoding.permute(0, 3, 1, 2), kernel_size=(1, stride))
        map_encoding = map_encoding.permute(0, 2, 3, 1).reshape(B, -1, D)

        # segment mask
        map_mask = torch.eq(map, 0)[:, :, :, 0].reshape(B, N_e, N_p//stride, N_p//(N_p//stride))
        map_mask = torch.max(map_mask, dim=-1)[0].reshape(B, -1)

        return map_encoding, map_mask

    def forward(self, inputs):
        # agent encoding
        ego = inputs['ego_state']
        neighbors = inputs['neighbors_state']
        actors = torch.cat([inputs['ego_state'].unsqueeze(1), neighbors], dim=1)
        encoded_ego = self.ego_encoder(ego)
        encoded_neighbors = [self.agent_encoder(neighbors[:, i]) for i in range(neighbors.shape[1])]
        encoded_actors = torch.stack([encoded_ego] + encoded_neighbors, dim=1)
        actors_mask = torch.eq(actors[:, :, -1].sum(-1), 0)

        # map encoding
        map_lanes = inputs['map_lanes']
        map_crosswalks = inputs['map_crosswalks']
        encoded_map_lanes = self.lane_encoder(map_lanes)
        encoded_map_crosswalks = self.crosswalk_encoder(map_crosswalks)

        # attention fusion
        encodings = []
        masks = []
        N = self._neighbors + 1
        assert actors.shape[1] >= N, 'Too many neighbors to predict'

        for i in range(N):
            lanes, lanes_mask = self.segment_map(map_lanes[:, i], encoded_map_lanes[:, i])
            crosswalks, crosswalks_mask = self.segment_map(map_crosswalks[:, i], encoded_map_crosswalks[:, i])
            fusion_input = torch.cat([encoded_actors, lanes, crosswalks], dim=1)
            mask = torch.cat([actors_mask, lanes_mask, crosswalks_mask], dim=1)
            masks.append(mask)
            encoding = fusion_input
            encodings.append(encoding)

        # outputs
        encodings = torch.stack(encodings, dim=1)
        masks = torch.stack(masks, dim=1)
        encoder_outputs = {
            'actors': actors,
            'encodings': encodings,
            'masks': masks
        }
        
        if 'act' in inputs.keys():
            encoder_outputs['act'] = inputs['act']

        return encoder_outputs

class Encoder_02_2(nn.Module):
    def __init__(self, neighbors_to_predict, layers=6, act=False):
        super(Encoder_02_2, self).__init__()
        heads, dim, dropout = 8, 256, 0.1
        self._neighbors = neighbors_to_predict
        attention_layer = nn.TransformerEncoderLayer(d_model=dim, nhead=heads, dim_feedforward=dim*4,
                                                     activation=F.gelu, dropout=dropout, batch_first=True)
        self.fusion_encoder = nn.TransformerEncoder(attention_layer, layers, enable_nested_tensor=False)
        self.act = act
        if act:
            print("ACT ENCODER ACTIVATED")
            self.act = act
            self.act_encoder = nn.Embedding(5, 256, padding_idx=0)
            
    def forward(self, inputs):
        masks_ = inputs['masks']
        encodings_ = inputs['encodings']
        actors = inputs['actors']
        # attention fusion
        encodings = []
        masks = []
        N = self._neighbors + 1
        assert actors.shape[1] >= N, 'Too many neighbors to predict'
        for i in range(N):
            if self.act:
                if i!=0:
                    # encoded_act = torch.zeros((inputs['act'].shape[0], 256), device=inputs['act'].device)
                    # encoded_act_mask = torch.ones_like(inputs['act'][:,i]).bool()
                    encoded_act = torch.zeros_like(inputs['act'])
                    encoded_act_mask = torch.ones_like(inputs['act'][:,i]).bool()
                else:
                    # encoded_act = self.act_encoder(inputs['act'][:,i].int())
                    # encoded_act_mask = torch.zeros_like(inputs['act'][:,i]).bool() #torch.zeros(inputs['act'][:,i].shape, device=encoded_act.device).bool()
                    encoded_act = self.act_encoder(inputs['act'])
                    encoded_act_mask = torch.zeros_like(inputs['act'][:,i]).bool() #torch.zeros(inputs['act'][:,i].shape, device=encoded_act.device).bool()
                
                fusion_input = torch.cat([encodings_[:,i], encoded_act[:,None]], dim=1)
                mask = torch.cat([masks_[:,i], encoded_act_mask[:,None]], dim=1)
            else:
                fusion_input = encodings_[:,i]
                mask = masks_[:,i]
            masks.append(mask)
            encoding = self.fusion_encoder(fusion_input, src_key_padding_mask=mask)
            encodings.append(encoding)

        # outputs
        encodings = torch.stack(encodings, dim=1)
        masks = torch.stack(masks, dim=1)
        encoder_outputs = {
            'actors': actors,
            'encodings': encodings,
            'masks': masks
        }
        
        if 'act' in inputs.keys():
            encoder_outputs['act'] = inputs['act']
        if 'query_act' in inputs.keys():
            encoder_outputs['query_act'] = inputs['query_act']

        return encoder_outputs

class Decoder_2(nn.Module):
    def __init__(self, modalities, future_len, neighbors_to_predict, levels=3, act=False):
        super(Decoder_2, self).__init__()
        self._levels = levels
        self._neighbors = neighbors_to_predict
        future_encoder = FutureEncoder()
        self.initial_stage = InitialDecoder_2(modalities, neighbors_to_predict, future_len, act=act)
        self.interaction_stage = nn.ModuleList([InteractionDecoder(future_encoder, future_len) for _ in range(levels)])
        self.act = act

    def forward(self, encoder_inputs):
        decoder_outputs = {}
        N = self._neighbors + 1
        assert encoder_inputs['actors'].shape[1] >= N, 'Too many neighbors to predict'

        current_states = encoder_inputs['actors'][:, :, -1]
        encodings, masks = encoder_inputs['encodings'], encoder_inputs['masks']

        # level 0
        if self.act:
            results = []
            i=0
            results.append(self.initial_stage(i, current_states[:, i], encodings[:, i], masks[:, i], encoder_inputs['query_act']))
            # results.append(self.initial_stage(i, current_states[:, i], encodings[:, i], masks[:, i], encoder_inputs['act'][:, i]))
            i=1
            results.append(self.initial_stage(i, current_states[:, i], encodings[:, i], masks[:, i], None))
            # results = [self.initial_stage(i, current_states[:, i], encodings[:, i], masks[:, i], encoder_inputs['act'][:, i]) for i in range(N)]
        else:
            results = [self.initial_stage(i, current_states[:, i], encodings[:, i], masks[:, i]) for i in range(N)]
        last_content = torch.stack([result[0] for result in results], dim=1) # query content [batch, N=2 agents, M modalities, dim=256]
        last_level = torch.stack([result[1] for result in results], dim=1) # GMM [batch, N=2, M, future T steps, 4 represent GMM parameters]
        last_scores = torch.stack([result[2] for result in results], dim=1) # [batch, 2, N, M]
        decoder_outputs['level_0_interactions'] = last_level
        decoder_outputs['level_0_scores'] = last_scores
        
        # level k reasoning
        for k in range(1, self._levels+1):
            interaction_decoder = self.interaction_stage[k-1]
            results = [interaction_decoder(i, current_states[:, :N], last_level, last_scores, \
                       last_content[:, i], encodings[:, i], masks[:, i]) for i in range(N)]
            last_content = torch.stack([result[0] for result in results], dim=1)
            last_level = torch.stack([result[1] for result in results], dim=1)
            last_scores = torch.stack([result[2] for result in results], dim=1)
            decoder_outputs[f'level_{k}_interactions'] = last_level
            decoder_outputs[f'level_{k}_scores'] = last_scores

        return decoder_outputs

class GameFormer_2(nn.Module):
    def __init__(self, modalities, neighbors_to_predict, future_len, encoder_layers=6, decoder_levels=4, act=False, act_dec=False):
        super(GameFormer_2, self).__init__()
        self.encoder_01 = Encoder_01_2(neighbors_to_predict, encoder_layers, act)
        self.encoder_02 = Encoder_02_2(neighbors_to_predict, encoder_layers, act)
        self.decoder = Decoder_2(modalities, future_len, neighbors_to_predict, decoder_levels, act_dec)

    def forward(self, inputs):
        encoder_outputs = self.encoder_01(inputs)
        encoder_outputs = self.encoder_02(encoder_outputs)
        outputs = self.decoder(encoder_outputs)

        return outputs

